Format registry as list
Sage-Bionetworks/Genie pull request #195
Opened 2019-09-17 18:32 UTC by kdaily

2019-09-19 22:21 UTC, thomasyu888 requested changes

2019-09-19 22:21 UTC, thomasyu888 commented on genie/validate.py
> +        logger.debug(f"checking {cls}.")
```suggestion
        logger.debug("checking {}.".format(cls))
```

2019-09-19 22:21 UTC, thomasyu888 commented on genie/validate.py
> +        logger.debug(f"checking {cls}.")
Support python 3.5 for now.

2019-09-19 22:21 UTC, thomasyu888 commented on genie/validate.py
> +    logger.debug(f"Using {format_registry} file formats.")
```suggestion
    logger.debug("Using {} file formats.".format(format_registry))
```

2019-09-19 22:21 UTC, thomasyu888 commented on genie/validate.py
> +    format_registry = collect_format_types(args.format_registry_packages)
Need to add `args.format_registry_packages` to `__main__.py`

2019-09-20 14:18 UTC, thomasyu888 reviewed
Would determining which file formats to validate and process come after collecting all file formats.  That is if we were to add a parameter like include/exclude types, where should the filtering happen?

2019-09-20 14:24 UTC, kdaily commented
I don't think so. There's no way to a priori know which files to get via `get_center_input_files`. I would:

1. Get all center input files
2. Determine their file type
3. Filter based on include/exclude

2019-09-20 14:31 UTC, thomasyu888 commented
The issue with that is that there are tons of vcf files. So I don't want to necessarily download them.

2019-09-20 14:35 UTC, kdaily commented
Agree - but relying on the file name (without using the `determineFiletype` function(s)) to determine the type is not going to work. Is it the case currently that you can use the entity name, NOT the file handle file name, to determine the file type?

2019-09-20 14:36 UTC, thomasyu888 commented
Ah I see what you're saying. Yes we can infer the file type with the entity name.  I know I used to call syn.get twice. Once to get the entity name and once to actually download the file. Not sure if this has changed.

2019-09-20 14:47 UTC, kdaily commented
`get_center_input_files` could do that, with a `download` parameter passed on to the `syn.get` call.

However, I was thinking that to simplify much of the other code, that the entity itself can be used to carry updated information as it moves through validation and processing (it's mutable). If the entity is retrieved multiple times this would be difficult to manage - but a wrapper object could be used.

1. `syn.get(..., download=False)` -> entity
2. `determineFiletype` updates the entity with the fileType
3. filter the entity based on the file type
4. download the entity for validation or processing and update any info added.

Proposed wrapper could be something like `GenieEntity(entity=entity, info=dict(fileType='vcf', ...))`. Provide a replace entity function that checks to be sure the same entity ID/version is supplied?

2019-09-20 18:09 UTC, thomasyu888 approved these changes

2019-09-20 18:10 UTC, merged