Separate maf database creation from cli
Sage-Bionetworks/Genie pull request #220
Opened 2019-11-21 23:49 UTC by kdaily

Creating a MAF database should happen separately - it has no dependence on the rest of the arguments or processing. This PR moves the code to create a MAF database to a new command line tool and removes the functionality from `input_to_database`.

2019-11-22 23:10 UTC, thomasyu888 commented
This is definitely a good move.  This was merely for 'convenience' as I would always process maf or vcf first.  There should really be a separate batch job that is: 'create maf db' and that gets run before anything else when new processing starts.

I like this revision, but will have to add/revise batch jobs

2019-11-22 23:18 UTC, kdaily commented
Thanks! And yes it will require changes to the infrastructure. Can I merge this and open a separate issue (here and/or in the Genie AWS infra repo) to fix that?

2019-11-22 23:30 UTC, thomasyu888 approved these changes

2019-11-25 21:10 UTC, thomasyu888 requested changes

2019-11-25 21:10 UTC, thomasyu888 commented on bin/create_maf_database.py
> +    syn = process_functions.synLogin(pemfile, debug=debug)
Missing debug parameter

2019-11-25 21:10 UTC, thomasyu888 commented on bin/create_maf_database.py
> +    parser.add_argument('--db_mapping_id', type=str,
Will this just be projectid at some point since we will be adding this as an annotation?

2019-12-18 22:41 UTC, thomasyu888 commented
@kdaily, must also add to setup.py

2020-02-12 18:52 UTC, thomasyu888 commented on bin/create_maf_database.py
> +    parser.add_argument('--db_mapping_id', type=str,
Will update this parameter once this is fixed: #222

2020-02-12 19:28 UTC, thomasyu888 commented
The true functionality of this function is
* Create a new table for a specific file format
* Replace the database mapping table with the newly created table.

2020-04-03 02:03 UTC, closed without merging