Implement SAMPLE_ID validation
Sage-Bionetworks/Genie pull request #444
Opened 2022-02-25 03:41 UTC by thomasyu888

* SAMPLE_ID must start with GENIE-CENTER-...
* SAMPLE_ID must have less than 50 characters

2022-04-28 07:59 UTC, thomasyu888 commented
@hhunterzinck This can be reviewed, but do not merge yet.  We will wait until after the public release to merge

2022-04-28 15:52 UTC, hhunterzinck requested changes
@thomasyu888 I was trying to run with the SAGE test files but got tripped up since SAGE isn't a valid center in the reference table (syn10061452) from which the configuration loads the list of valid centers.  

`genie validate data_clinical_supp_SAGE.txt SAGE`

output the following error:

> Traceback (most recent call last):
>   File "/Users/hhunterzinck/opt/anaconda3/envs/genie/bin/genie", line 8, in <module>
>     sys.exit(main())
>   File "/Users/hhunterzinck/opt/anaconda3/envs/Genie/lib/python3.8/site-packages/genie/__main__.py", line 176, in main
>     args.func(syn, args)
>   File "/Users/hhunterzinck/opt/anaconda3/envs/Genie/lib/python3.8/site-packages/genie/validate.py", line 212, in _perform_validate
>     _check_center_input(args.center, list(genie_config["center_config"].keys()))
>   File "/Users/hhunterzinck/opt/anaconda3/envs/Genie/lib/python3.8/site-packages/genie/validate.py", line 175, in _check_center_input
>     raise ValueError(
> ValueError: Must specify one of these centers: JHU, DFCI, GRCC, NKI, MSK, UHN, VICC, MDA, WAKE, YALE, UCSF, CRUK, CHOP, VHIO, SCI, PROV, COLU, UCHI, DUKE

Could the SAGE site be included for testing without disrupting production processing of other sites?

2022-04-28 15:52 UTC, hhunterzinck commented on genie/process_functions.py
> +    if any(identifiers.str.len() > 50):
```suggestion
    if any(identifiers.str.len() >= 50):
```

2022-04-28 15:52 UTC, hhunterzinck commented on genie_registry/clinical.py
> +            if any(clinicaldf[patientId].str.len() > 50):
```suggestion
            if any(clinicaldf[patientId].str.len() >= 50):
```

2022-04-28 18:07 UTC, thomasyu888 commented
@hhunterzinck make sure to set the correct --project_id. It defaults to main genie project id, but if you provide the test genie project id, sage will be included

2022-04-28 18:22 UTC, hhunterzinck approved these changes
Great, thanks!  Was able to use the appropriate test project to test invalid sample and patient IDs.  Looks great.

2022-04-28 18:24 UTC, thomasyu888 commented
Thanks for the review. This is another PR that should be merged after the public release

2022-05-26 05:10 UTC, thomasyu888 commented
Use _validate_genie function for structural variants

2022-07-02 19:50 UTC, merged