Use genie config in validation cli
Sage-Bionetworks/Genie pull request #461
Opened 2022-03-23 22:01 UTC by thomasyu888

2022-03-30 21:14 UTC, hhunterzinck requested changes

2022-03-30 21:14 UTC, hhunterzinck commented on genie/validate.py
> +    _check_parentid_permission_container(syn=syn, project_id=args.parentid)
```suggestion
    _check_parentid_permission_container(syn=syn, parentid=args.parentid)
```

2022-03-31 15:04 UTC, hhunterzinck commented
@thomasyu888 This branch was still giving me errors when trying to run `genie validate --project_id syn7208886 data_clinical_supp_SAGE.txt SAGE`.  Could you try running it through to ensure syntax validity and then retag me for review?

2022-04-01 09:17 UTC, thomasyu888 commented
Thanks @hhunterzinck .  Your suggestion fixed the code.

2022-04-01 15:08 UTC, hhunterzinck approved these changes

2022-04-01 18:20 UTC, merged